---
chdir: /Users/Yosuke/Documents/rubyprog/github-twitter-integration
environment: development
port: 3000
timeout: 30
log: log/development.log
pid: tmp/pids/thin.pid
max_conns: 1024
max_persistent_conns: 100
require: []
wait: 30
threadpool_size: 20
daemonize: true
